Q1. Pandas version
What version of Pandas did you install?

You can get the version information using the __version__ field:

In [1]:

import pandas as pd

In [2]:
pd.__version__

'3.0.6'

Getting the data

In [3]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-26 20:54:09--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.5’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.01s

2026-09-26 20:54:09 (56.5 MB/s) - ‘car_fuel_efficiency_2026.csv.5’ saved [635180/635180]

Q2. Records count
How many records are in the dataset?

In [4]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [5]:
rows, columns = df.shape
print(f"Rows: {rows}, Columns: {columns}")

Rows: 10000, Columns: 11

Q3. Fuel types
How many fuel types are presented in the dataset?

In [6]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [7]:
df['fuel_type']

0       Gasoline
1         Diesel
2       Gasoline
3       Gasoline
4         Diesel
          ...
9995    Gasoline
9996    Gasoline
9997    Gasoline
9998      Hybrid
9999      Diesel
Name: fuel_type, Length: 10000, dtype: str

In [8]:
df['fuel_type'].nunique()

3

Q4. Missing values
How many columns in the dataset have missing values?

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [10]:
(df.isnull().sum() > 0).sum()

np.int64(2)

Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [11]:
df['origin']

0       Europe
1       Europe
2         Asia
3       Europe
4          USA
         ...
9995       USA
9996      Asia
9997       USA
9998       USA
9999       USA
Name: origin, Length: 10000, dtype: str

In [12]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6. Median value of horsepower
1. Find the median value of the horsepower column in the dataset.

In [13]:
df['horsepower'].median()

np.float64(254.0)

2. Next, calculate the most frequent value of the same horsepower column.

In [14]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [15]:
mode_hp = df['horsepower'].mode()[0]
df['horsepower'] = df['horsepower'].fillna(mode_hp)

4. Now, calculate the median value of horsepower once again.

In [16]:
df['horsepower'].isnull().sum()

np.int64(0)

In [17]:
df['horsepower'].median()

np.float64(252.0)

Q7. Sum of weights
1. Select all the cars from Asia

In [18]:
df[df['origin'] == 'Asia']

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

2. Select only columns vehicle_weight and model_year

In [19]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

3. Select the first 7 values

In [20]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

4. Get the underlying NumPy array. Let's call it X.

In [21]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values

In [22]:
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [23]:
X.shape

(7, 2)

In [24]:
X.T.shape

(2, 7)

In [25]:
XTX = X.T.dot(X)

In [26]:
XTX.shape

(2, 2)

6. Invert XTX.

In [27]:
import numpy as np

In [28]:
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [29]:
elements = [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array(elements)
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [30]:
w = (XTXinv.dot(X.T)).dot(y)

In [31]:
w

array([0.13644777, 0.2327492 ])

9. What's the sum of all the elements of the result?

In [32]:
w.sum()

np.float64(0.36919696904925486)